create database rktc_genai

use rktc_genai

CREATE TABLE HORSE_CATEGORIES (
    CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(100) NOT NULL
);

CREATE TABLE HORSES (
    HORSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    BIRTH_DATE DATE NOT NULL,
    GENDER ENUM('Male', 'Female') NOT NULL,
    COLOR VARCHAR(100),
    HEIGHT DECIMAL(5, 2),
    WEIGHT DECIMAL(5, 2),
    BIRTHMARKS TEXT,
    CATEGORY_ID INT,
    SIRE_ID INT,
    DAM_ID INT,
    HANDICAP_RATING DECIMAL(4, 2),
    FOREIGN KEY (CATEGORY_ID) REFERENCES HORSE_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (SIRE_ID) REFERENCES HORSES(HORSE_ID),
    FOREIGN KEY (DAM_ID) REFERENCES HORSES(HORSE_ID)
);

CREATE TABLE ORGANIZERS (
    ORGANIZER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255),
    ROLE VARCHAR(100),
    CONTACT VARCHAR(20)
);

CREATE TABLE RACES (
    RACE_ID INT AUTO_INCREMENT PRIMARY KEY,
    RACE_NAME VARCHAR(255) NOT NULL,
    LOCATION VARCHAR(255),
    RACE_DATE DATE NOT NULL,
    RACE_TIME TIME NOT NULL,
    CATEGORY_ID INT,
    ANNOUNCED_BY INT,
    FOREIGN KEY (CATEGORY_ID) REFERENCES HORSE_CATEGORIES(CATEGORY_ID),
    FOREIGN KEY (ANNOUNCED_BY) REFERENCES ORGANIZERS(ORGANIZER_ID)
);

CREATE TABLE RACES_WON (
    RACE_WIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    HORSE_ID INT,
    RACE_ID INT,
    POSITION INT,
    FOREIGN KEY (HORSE_ID) REFERENCES HORSES(HORSE_ID),
    FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID)
);

CREATE TABLE JOCKEYS (
    JOCKEY_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    AGE INT,
    EXPERIENCE_YEARS INT,
    WEIGHT DECIMAL(5, 2),
    HEIGHT DECIMAL(5, 2)
);

CREATE TABLE RACE_PARTICIPANTS (
    PARTICIPATION_ID INT AUTO_INCREMENT PRIMARY KEY,
    RACE_ID INT,
    HORSE_ID INT,
    JOCKEY_ID INT,
    STARTING_POSITION INT,
    HANDICAP DECIMAL(4, 2),
    FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID),
    FOREIGN KEY (HORSE_ID) REFERENCES HORSES(HORSE_ID),
    FOREIGN KEY (JOCKEY_ID) REFERENCES JOCKEYS(JOCKEY_ID)
);

CREATE TABLE CLUB_MEMBERS (
    MEMBER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255) NOT NULL,
    DOB DATE,
    ADDRESS TEXT,
    EMAIL VARCHAR(255),
    PHONE VARCHAR(20),
    MEMBERSHIP_START_DATE DATE NOT NULL,
    MEMBERSHIP_TYPE ENUM('Regular', 'VIP'),
    SUBSCRIPTION_FEE DECIMAL(10, 2)
);

CREATE TABLE PARTY_BOOKINGS (
    BOOKING_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT,
    EVENT_DATE DATE,
    VENUE VARCHAR(255),
    GUEST_COUNT INT,
    TOTAL_COST DECIMAL(10, 2),
    FOREIGN KEY (MEMBER_ID) REFERENCES CLUB_MEMBERS(MEMBER_ID)
);

CREATE TABLE FOOD_AND_DRINKS (
    ITEM_ID INT AUTO_INCREMENT PRIMARY KEY,
    ITEM_NAME VARCHAR(255),
    CATEGORY ENUM('Food', 'Drink'),
    PRICE DECIMAL(10, 2)
);

CREATE TABLE ORDERS (
    ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
    MEMBER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10, 2),
    FOREIGN KEY (MEMBER_ID) REFERENCES CLUB_MEMBERS(MEMBER_ID)
);

CREATE TABLE ORDER_DETAILS (
    ORDER_DETAIL_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDER_ID INT,
    ITEM_ID INT,
    QUANTITY INT,
    ITEM_PRICE DECIMAL(10, 2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (ITEM_ID) REFERENCES FOOD_AND_DRINKS(ITEM_ID)
);


CREATE TABLE ANNOUNCEMENTS (
    ANNOUNCEMENT_ID INT AUTO_INCREMENT PRIMARY KEY,
    RACE_ID INT,
    ANNOUNCEMENT_TEXT TEXT,
    ANNOUNCEMENT_DATE DATETIME,
    FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID)
);

CREATE TABLE ROLES (
    ROLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLE_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    PERMISSIONS JSON
);


CREATE TABLE USERS (
    USER_ID INT AUTO_INCREMENT PRIMARY KEY,
    FULL_NAME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    USERNAME VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PHONE_NUMBER VARCHAR(20),
    IS_ADMIN BOOLEAN DEFAULT FALSE,
    ROLE_ID INT,
    STATUS ENUM('Active', 'Inactive') DEFAULT 'Active',
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID)
);


CREATE TABLE ADMINS (
    ADMIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ASSIGNED_DATE DATE,
    ADMIN_TYPE ENUM('SuperAdmin', 'Manager'),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE LOGINS (
    LOGIN_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    LOGIN_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    LOGOUT_TIMESTAMP DATETIME,
    IP_ADDRESS VARCHAR(50),
    DEVICE_DETAILS VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE AUDIT_TRAIL (
    AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    ACTION_PERFORMED TEXT NOT NULL,
    TABLE_AFFECTED VARCHAR(100),
    RECORD_ID INT,
    ACTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS VARCHAR(50),
    REMARKS TEXT,
    FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

CREATE TABLE BETTING (
    BET_ID INT AUTO_INCREMENT PRIMARY KEY,
    RACE_ID INT,
    HORSE_ID INT,
    MEMBER_ID INT,
    BET_AMOUNT DECIMAL(10, 2),
    ODDS DECIMAL(5, 2),
    BET_OUTCOME ENUM('Win', 'Loss'),
    PAYOUT DECIMAL(10, 2),
    FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID),
    FOREIGN KEY (HORSE_ID) REFERENCES HORSES(HORSE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES CLUB_MEMBERS(MEMBER_ID)
);

CREATE TABLE TICKETS (
    TICKET_ID INT AUTO_INCREMENT PRIMARY KEY,
    RACE_ID INT,
    MEMBER_ID INT,
    TICKET_TYPE ENUM('General', 'VIP'),
    PRICE DECIMAL(10, 2),
    FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES CLUB_MEMBERS(MEMBER_ID)
);

CREATE TABLE RACE_RESULTS (
    RESULT_ID INT AUTO_INCREMENT PRIMARY KEY,
    RACE_ID INT,
    HORSE_ID INT,
    POSITION INT,
    TIME_TAKEN TIME,
    FOREIGN KEY (RACE_ID) REFERENCES RACES(RACE_ID),
    FOREIGN KEY (HORSE_ID) REFERENCES HORSES(HORSE_ID)
);

CREATE TABLE BETTING_PAYOUTS (
    PAYOUT_ID INT AUTO_INCREMENT PRIMARY KEY,
    BET_ID INT,
    AMOUNT DECIMAL(10, 2),
    PAYMENT_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BET_ID) REFERENCES BETTING(BET_ID)
);

-- SEED DATA

INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Thoroughbred');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Quarter Horse');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Arabian');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Standardbred');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Appaloosa');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Morgan');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Warmblood');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Draft Horse');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Shetland Pony');
INSERT INTO HORSE_CATEGORIES (CATEGORY_NAME) VALUES ('Clydesdale');


INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (1, 'Lightning Bolt', '2015-01-01', 'Female', 'Black', 14.2, 910, 'None', 2, NULL, NULL, 51.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (2, 'Thunderstorm', '2015-02-15', 'Male', 'Brown', 14.4, 920, 'White Star', 3, 1, NULL, 53.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (3, 'Majestic Star', '2015-04-01', 'Female', 'Chestnut', 14.6, 930, 'Blaze', 4, 2, 1, 54.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (4, 'Shadow Dancer', '2015-05-16', 'Male', 'Gray', 14.8, 940, 'Snip', 5, 3, 2, 56.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (5, 'Blazing Glory', '2015-06-30', 'Female', 'Bay', 15.0, 950, 'Stripe', 6, NULL, 3, 57.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (6, 'Golden Mane', '2015-08-14', 'Male', 'Palomino', 15.2, 960, 'Sock', 7, 5, 4, 59.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (7, 'Silver Sprint', '2015-09-28', 'Female', 'Dun', 15.4, 970, 'Stocking', 8, 6, NULL, 60.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (8, 'Night Whisper', '2015-11-12', 'Male', 'Buckskin', 15.6, 980, 'White Hoof', 9, 7, 5, 62.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (9, 'Storm Chaser', '2015-12-27', 'Female', 'Roan', 15.8, 990, 'Ermine Spots', 10, 8, 6, 63.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (10, 'Royal Pride', '2016-02-10', 'Male', 'Piebald', 16.0, 989, 'White Pastern', 1, NULL, 7, 65.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (11, 'Dawn Breaker', '2016-03-26', 'Female', 'Skewbald', 14.2, 960, 'Half Pastern', 2, 10, 8, 66.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (12, 'Moonlight Echo', '2016-05-10', 'Male', 'Grullo', 14.4, 972, 'Coronet Band', 3, 11, 9, 68.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (13, 'Phoenix Flame', '2016-06-24', 'Female', 'Sorrel', 14.6, 950, 'Dorsal Stripe', 4, 12, NULL, 69.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (14, 'Ocean Breeze', '2016-08-08', 'Male', 'Cremello', 14.8, 978, 'Shoulder Stripe', 5, 13, 10, 71.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (15, 'Desert Mirage', '2016-09-22', 'Female', 'Perlino', 15.0, 989, 'Bald Face', 6, NULL, 11, 72.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (16, 'Mountain Thunder', '2016-11-06', 'Male', 'Liver Chestnut', 15.2, 991, 'Medicine Hat', 7, 15, 12, 74.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (17, 'Emerald Flash', '2016-12-21', 'Female', 'Flaxen Chestnut', 15.4, 941, 'Faint Star', 8, 16, 13, 75.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (18, 'Ruby Runner', '2017-02-04', 'Male', 'Dark Bay', 15.6, 959, 'White Chin', 9, 17, NULL, 77.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (19, 'Sapphire Sky', '2017-03-21', 'Female', 'Light Bay', 15.8, 969, 'Dark Muzzle', 10, 18, 15, 78.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (20, 'Diamond Dash', '2017-05-05', 'Male', 'Blue Roan', 16.0, 671, 'Dark Hooves', 1, NULL, 16, 80.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (21, 'Horse 21', '2017-01-01', 'Female', 'Palomino', 14.2, 873, 'Stocking', 6, 7, 18, 77.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (22, 'Horse 22', '2017-04-01', 'Male', 'Chestnut', 14.8, 898, 'White Hoof', 10, 5, 2, 75.1);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (23, 'Horse 23', '2017-06-30', 'Female', 'Cremello', 14.9, 943, 'None', 1, 6, 19, 68.2);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (24, 'Horse 24', '2017-09-28', 'Male', 'Chestnut', 15.9, 882, 'White Star', 8, 19, 20, 63.1);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (25, 'Horse 25', '2017-12-27', 'Female', 'Dun', 14.4, 910, 'Half Pastern', 6, 16, 18, 57.7);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (26, 'Horse 26', '2018-03-27', 'Male', 'Bay', 15.3, 951, 'Stripe', 7, 8, 12, 61.2);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (27, 'Horse 27', '2018-06-25', 'Female', 'Buckskin', 15.1, 982, 'Blaze', 3, 19, 13, 71.4);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (28, 'Horse 28', '2018-09-23', 'Male', 'Gray', 15.6, 905, 'Snip', 4, 17, 9, 77.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (29, 'Horse 29', '2018-12-22', 'Female', 'Grullo', 15.7, 998, 'White Pastern', 2, 15, 18, 65.8);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (30, 'Horse 30', '2019-03-22', 'Male', 'Roan', 14.9, 890, 'Coronet Band', 5, 16, 11, 64.3);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (31, 'Horse 31', '2019-06-20', 'Female', 'Cremello', 14.8, 874, 'Sock', 6, 18, 10, 55.6);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (32, 'Horse 32', '2019-09-18', 'Male', 'Bay', 15.4, 899, 'Stocking', 10, 11, 14, 62.1);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (33, 'Horse 33', '2019-12-17', 'Female', 'Buckskin', 14.5, 972, 'White Chin', 4, 12, 19, 73.2);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (34, 'Horse 34', '2020-03-16', 'Male', 'Brown', 14.6, 881, 'Blaze', 8, 14, 13, 69.0);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (35, 'Horse 35', '2020-06-14', 'Female', 'Grullo', 15.5, 907, 'Half Pastern', 3, 9, 17, 61.5);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (36, 'Horse 36', '2020-09-12', 'Male', 'Palomino', 15.8, 895, 'Stripe', 2, 16, 18, 64.2);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (37, 'Horse 37', '2020-12-11', 'Female', 'Chestnut', 15.3, 880, 'White Hoof', 7, 18, 14, 70.8);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (38, 'Horse 38', '2021-03-11', 'Male', 'Roan', 14.7, 921, 'Ermine Spots', 9, 20, 17, 59.9);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (39, 'Horse 39', '2021-06-09', 'Female', 'Gray', 15.1, 950, 'Dorsal Stripe', 10, 11, 18, 66.4);

INSERT INTO HORSES (HORSE_ID, NAME, BIRTH_DATE, GENDER, COLOR, HEIGHT, WEIGHT, BIRTHMARKS, CATEGORY_ID, SIRE_ID, DAM_ID, HANDICAP_RATING)
VALUES (40, 'Horse 40', '2021-09-07', 'Male', 'Buckskin', 15.6, 975, 'White Pastern', 4, 15, 13, 78.3);

-- Remaining rows continue similarly

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (1, 'John Smith', 'Race Announcer', '555-123-4567');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (2, 'Emma Johnson', 'Club Manager', '555-234-5678');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (3, 'Michael Brown', 'Event Coordinator', '555-345-6789');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (4, 'Sophia Davis', 'Logistics Manager', '555-456-7890');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (5, 'William Wilson', 'Marketing Manager', '555-567-8901');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (6, 'Olivia Martinez', 'Financial Advisor', '555-678-9012');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (7, 'James Anderson', 'Race Coordinator', '555-789-0123');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (8, 'Isabella Thomas', 'Volunteer Manager', '555-890-1234');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (9, 'Liam Taylor', 'Sponsorship Manager', '555-901-2345');

INSERT INTO ORGANIZERS (ORGANIZER_ID, FULL_NAME, ROLE, CONTACT)
VALUES (10, 'Mia White', 'Safety Officer', '555-012-3456');

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (1, 'Race 1', 'Dallas', '2025-01-11', '15:00:00', 6, 9);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (2, 'Race 2', 'Chicago', '2025-01-21', '12:00:00', 7, 9);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (3, 'Race 3', 'Los Angeles', '2025-01-31', '10:30:00', 7, 10);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (4, 'Race 4', 'Los Angeles', '2025-02-10', '14:30:00', 8, 7);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (5, 'Race 5', 'Los Angeles', '2025-02-20', '18:00:00', 3, 10);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (6, 'Race 6', 'Dallas', '2025-03-02', '15:30:00', 4, 5);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (7, 'Race 7', 'Miami', '2025-03-12', '13:00:00', 6, 6);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (8, 'Race 8', 'Los Angeles', '2025-03-22', '15:00:00', 8, 3);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (9, 'Race 9', 'Chicago', '2025-04-01', '15:00:00', 6, 5);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (10, 'Race 10', 'Miami', '2025-04-11', '17:30:00', 1, 6);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (11, 'Race 11', 'Chicago', '2025-04-21', '14:30:00', 1, 4);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (12, 'Race 12', 'Dallas', '2025-05-01', '17:00:00', 3, 5);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (13, 'Race 13', 'New York', '2025-05-11', '12:00:00', 7, 7);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (14, 'Race 14', 'Los Angeles', '2025-05-21', '12:00:00', 3, 8);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (15, 'Race 15', 'Dallas', '2025-05-31', '10:00:00', 10, 9);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (16, 'Race 16', 'Los Angeles', '2025-06-10', '18:30:00', 7, 2);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (17, 'Race 17', 'Miami', '2025-06-20', '15:00:00', 9, 5);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (18, 'Race 18', 'New York', '2025-06-30', '18:00:00', 1, 6);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (19, 'Race 19', 'Dallas', '2025-07-10', '15:30:00', 7, 3);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (20, 'Race 20', 'Dallas', '2025-07-20', '12:30:00', 7, 5);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (21, 'Race 21', 'New York', '2025-07-30', '10:00:00', 9, 5);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (22, 'Race 22', 'Miami', '2025-08-09', '17:00:00', 3, 4);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (23, 'Race 23', 'Los Angeles', '2025-08-19', '11:30:00', 10, 1);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (24, 'Race 24', 'Miami', '2025-08-29', '13:00:00', 8, 1);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (25, 'Race 25', 'Miami', '2025-09-08', '10:30:00', 1, 9);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (26, 'Race 26', 'Chicago', '2025-09-18', '18:00:00', 6, 4);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (27, 'Race 27', 'Miami', '2025-09-28', '18:30:00', 8, 9);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (28, 'Race 28', 'New York', '2025-10-08', '15:00:00', 3, 9);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (29, 'Race 29', 'Los Angeles', '2025-10-18', '13:00:00', 4, 2);

INSERT INTO RACES (RACE_ID, RACE_NAME, LOCATION, RACE_DATE, RACE_TIME, CATEGORY_ID, ANNOUNCED_BY)
VALUES (30, 'Race 30', 'New York', '2025-10-28', '10:00:00', 8, 4);

INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (1, 45, 15, 7);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (2, 5, 15, 5);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (3, 48, 1, 5);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (4, 4, 10, 5);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (5, 23, 9, 1);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (6, 3, 22, 2);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (7, 37, 15, 1);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (8, 32, 27, 3);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (9, 43, 18, 10);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (10, 46, 2, 5);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (11, 31, 6, 3);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (12, 34, 13, 2);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (13, 4, 5, 3);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (14, 3, 8, 4);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (15, 39, 1, 6);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (16, 29, 16, 4);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (17, 40, 2, 7);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (18, 30, 24, 1);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (19, 25, 2, 9);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (20, 38, 14, 10);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (21, 17, 30, 1);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (22, 24, 9, 10);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (23, 42, 22, 7);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (24, 23, 22, 10);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (25, 26, 24, 3);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (26, 5, 18, 9);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (27, 28, 13, 8);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (28, 26, 30, 7);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (29, 24, 26, 9);
INSERT INTO RACES_WON (RACE_WIN_ID, HORSE_ID, RACE_ID, POSITION) VALUES (30, 41, 14, 4);

select * from RACES_WON

alter table JOCKEYS add column EXPERIENCE decimal(10,2)


INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (1, 'James Smith', 25, 5, 55.2, 162.3);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (2, 'John Johnson', 28, 7, 57.5, 165.0);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (3, 'Robert Williams', 32, 10, 59.3, 167.8);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (4, 'Michael Brown', 24, 3, 56.0, 160.4);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (5, 'William Jones', 27, 8, 58.7, 164.6);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (6, 'David Garcia', 30, 12, 62.1, 170.0);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (7, 'Joseph Miller', 35, 15, 60.4, 172.1);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (8, 'Thomas Davis', 29, 11, 55.9, 161.3);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (9, 'Charles Rodriguez', 26, 6, 54.2, 158.7);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (10, 'Christopher Martinez', 33, 14, 63.0, 175.4);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (11, 'Daniel Hernandez', 22, 2, 52.5, 156.8);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (12, 'Matthew Lopez', 31, 9, 58.3, 164.0);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (13, 'Anthony Gonzalez', 34, 16, 61.5, 173.6);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (14, 'Mark Wilson', 36, 18, 64.8, 177.1);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (15, 'Paul Anderson', 20, 1, 53.6, 159.9);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (16, 'Steven Thomas', 23, 4, 56.7, 162.8);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (17, 'Andrew Taylor', 28, 7, 57.9, 163.5);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (18, 'Kenneth Moore', 27, 6, 58.0, 164.3);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (19, 'Joshua White', 24, 3, 56.4, 161.1);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (20, 'Kevin Lee', 32, 10, 59.1, 166.0);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (21, 'Brian Harris', 29, 11, 60.8, 168.5);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (22, 'George Clark', 33, 13, 62.3, 171.6);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (23, 'Edward Lewis', 35, 17, 63.9, 173.8);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (24, 'Ronald Walker', 21, 2, 53.1, 157.4);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (25, 'Timothy Hall', 37, 19, 64.5, 176.3);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (26, 'Jason Allen', 34, 15, 61.2, 172.4);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (27, 'Jeffrey Young', 26, 8, 55.3, 161.0);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (28, 'Ryan King', 30, 12, 59.4, 167.2);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (29, 'Jacob Wright', 25, 5, 57.6, 163.9);
INSERT INTO JOCKEYS (JOCKEY_ID, FULL_NAME, AGE, EXPERIENCE, WEIGHT, HEIGHT) VALUES (30, 'Gary Scott', 22, 3, 54.8, 160.5);

INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (1, 10, 8, 5, 5, 2.51);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (2, 25, 17, 28, 9, 0.29);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (3, 28, 20, 25, 2, 7.21);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (4, 20, 30, 4, 14, 3.71);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (5, 24, 9, 18, 15, 6.43);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (6, 27, 32, 18, 15, 7.80);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (7, 13, 33, 5, 10, 2.36);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (8, 5, 3, 22, 1, 4.79);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (9, 3, 15, 28, 7, 5.67);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (10, 12, 8, 26, 10, 9.51);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (11, 4, 2, 15, 4, 3.10);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (12, 6, 4, 11, 4, 3.99);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (13, 25, 32, 8, 5, 2.66);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (14, 17, 11, 4, 7, 3.33);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (15, 6, 26, 9, 14, 6.32);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (16, 1, 31, 20, 7, 8.82);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (17, 22, 27, 3, 5, 8.76);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (18, 26, 31, 7, 2, 9.27);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (19, 18, 28, 30, 8, 6.95);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (20, 16, 19, 6, 4, 7.02);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (21, 10, 8, 14, 1, 0.57);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (22, 2, 1, 17, 5, 6.92);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (23, 11, 13, 10, 8, 8.54);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (24, 27, 3, 10, 2, 8.84);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (25, 16, 31, 14, 5, 7.85);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (26, 18, 16, 28, 3, 3.09);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (27, 28, 20, 27, 5, 4.49);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (28, 2, 7, 19, 1, 3.05);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (29, 23, 18, 23, 4, 3.64);
INSERT INTO RACE_PARTICIPANTS (PARTICIPATION_ID, RACE_ID, HORSE_ID, JOCKEY_ID, STARTING_POSITION, HANDICAP) VALUES (30, 5, 32, 23, 12, 2.28);


INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (1, 'James Smith', '1980-05-12', '123 Elm Street', 'james.smith@example.com', '555-123-4567', '2021-03-15', 'Regular', 800.50);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (2, 'Emma Johnson', '1985-11-22', '456 Maple Avenue', 'emma.johnson@example.com', '555-234-5678', '2020-07-20', 'VIP', 2000.75);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (3, 'Michael Brown', '1978-04-18', '789 Oak Lane', 'michael.brown@example.com', '555-345-6789', '2022-01-10', 'Regular', 950.25);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (4, 'Sophia Davis', '1990-08-14', '321 Pine Street', 'sophia.davis@example.com', '555-456-7890', '2021-06-30', 'VIP', 2200.00);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (5, 'William Wilson', '1982-03-05', '654 Cedar Drive', 'william.wilson@example.com', '555-567-8901', '2020-10-25', 'Regular', 870.00);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (6, 'Olivia Martinez', '1995-12-30', '987 Birch Way', 'olivia.martinez@example.com', '555-678-9012', '2022-04-01', 'VIP', 2500.60);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (7, 'Liam Taylor', '1975-07-23', '432 Spruce Street', 'liam.taylor@example.com', '555-789-0123', '2021-09-15', 'Regular', 760.40);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (8, 'Isabella Anderson', '1988-02-11', '111 Aspen Road', 'isabella.anderson@example.com', '555-890-1234', '2020-03-10', 'VIP', 2300.85);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (9, 'Noah Thomas', '1992-06-19', '222 Elm Street', 'noah.thomas@example.com', '555-901-2345', '2021-12-05', 'Regular', 980.30);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (10, 'Mia White', '1984-09-28', '333 Maple Avenue', 'mia.white@example.com', '555-012-3456', '2022-06-01', 'VIP', 2100.50);

-- Adding more entries
INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (11, 'Ethan Harris', '1991-03-17', '444 Oak Lane', 'ethan.harris@example.com', '555-123-6789', '2021-07-10', 'Regular', 870.90);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (12, 'Ava Clark', '1989-11-30', '555 Pine Street', 'ava.clark@example.com', '555-234-7890', '2020-11-15', 'VIP', 2400.70);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (13, 'Lucas Lewis', '1983-05-08', '666 Cedar Drive', 'lucas.lewis@example.com', '555-345-8901', '2022-08-10', 'Regular', 910.50);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (14, 'Charlotte Walker', '1990-02-14', '777 Birch Way', 'charlotte.walker@example.com', '555-456-9012', '2021-04-20', 'VIP', 2005.20);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (15, 'Henry Hall', '1976-08-27', '888 Spruce Street', 'henry.hall@example.com', '555-567-0123', '2020-06-15', 'Regular', 780.60);

INSERT INTO CLUB_MEMBERS (MEMBER_ID, FULL_NAME, DOB, ADDRESS, EMAIL, PHONE, MEMBERSHIP_START_DATE, MEMBERSHIP_TYPE, SUBSCRIPTION_FEE)
VALUES (16, 'Amelia Allen', '1993-01-03', '999 Aspen Road', 'amelia.allen@example.com', '555-678-1234', '2022-05-01', 'VIP', 2650.45);

-- Add more rows if necessary

INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (1, 14, '2025-09-22', 'Grand Hall', 195, 1060.38);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (2, 3, '2025-05-23', 'Banquet Room', 153, 2848.37);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (3, 10, '2025-08-29', 'Private Lounge', 48, 8809.26);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (4, 12, '2025-07-22', 'Grand Hall', 142, 9039.83);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (5, 12, '2025-05-15', 'Grand Hall', 52, 6660.51);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (6, 15, '2025-03-01', 'Banquet Room', 20, 5874.16);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (7, 9, '2025-05-25', 'Grand Hall', 63, 5296.31);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (8, 4, '2025-02-07', 'Garden Terrace', 22, 5931.43);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (9, 15, '2025-12-18', 'Banquet Room', 42, 9503.14);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (10, 8, '2025-08-15', 'Garden Terrace', 36, 6230.35);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (11, 11, '2025-01-17', 'Grand Hall', 174, 9302.42);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (12, 8, '2025-06-24', 'Private Lounge', 41, 9379.48);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (13, 7, '2025-01-13', 'Banquet Room', 127, 9247.96);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (14, 4, '2025-07-31', 'Grand Hall', 129, 3096.61);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (15, 2, '2025-10-06', 'Private Lounge', 60, 1899.66);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (16, 3, '2025-04-03', 'Grand Hall', 198, 2216.12);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (17, 5, '2025-04-24', 'Garden Terrace', 119, 6039.19);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (18, 1, '2025-03-25', 'Grand Hall', 155, 9198.56);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (19, 14, '2025-09-08', 'Private Lounge', 15, 4195.71);
INSERT INTO PARTY_BOOKINGS (BOOKING_ID, MEMBER_ID, EVENT_DATE, VENUE, GUEST_COUNT, TOTAL_COST) VALUES (20, 7, '2025-05-17', 'Banquet Room', 148, 6997.98);

INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (1, 'Cappuccino', 40.90, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (2, 'Fish and Chips', 8.40, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (3, 'Pina Colada', 42.49, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (4, 'Cheeseburger', 6.88, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (5, 'Latte', 35.59, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (6, 'Martini', 19.88, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (7, 'Old Fashioned', 11.53, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (8, 'Spaghetti Carbonara', 11.38, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (9, 'Cappuccino', 39.30, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (10, 'Beef Steak', 7.65, 'Food');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (11, 'Vanilla Ice Cream', 10.61, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (12, 'Vanilla Ice Cream', 16.13, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (13, 'Lemon Tart', 44.57, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (14, 'Martini', 46.87, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (15, 'Spaghetti Carbonara', 33.66, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (16, 'Cheeseburger', 26.26, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (17, 'French Fries', 8.02, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (18, 'Pina Colada', 48.64, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (19, 'Vanilla Ice Cream', 33.40, 'Drink');
INSERT INTO FOOD_AND_DRINKS (ITEM_ID, ITEM_NAME, PRICE, CATEGORY) VALUES (20, 'Margherita Pizza', 22.83, 'Drink');

INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (1, 14, '2025-06-17', 302.56);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (2, 1, '2025-01-08', 391.05);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (3, 13, '2025-01-16', 385.12);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (4, 9, '2025-02-28', 410.07);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (5, 8, '2025-01-24', 254.65);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (6, 11, '2025-10-17', 102.85);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (7, 14, '2025-12-17', 183.16);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (8, 14, '2025-10-04', 333.85);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (9, 10, '2025-08-05', 347.73);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (10, 5, '2025-09-02', 301.65);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (11, 6, '2025-10-02', 199.47);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (12, 5, '2025-04-08', 141.32);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (13, 5, '2025-01-31', 221.86);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (14, 3, '2025-11-30', 448.91);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (15, 15, '2025-06-02', 341.49);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (16, 13, '2025-02-08', 348.19);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (17, 3, '2025-06-27', 160.24);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (18, 14, '2025-12-17', 355.35);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (19, 16, '2025-04-26', 121.85);
INSERT INTO ORDERS (ORDER_ID, MEMBER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES (20, 13, '2025-03-10', 194.93);


INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (1, 10, 1, 3, 7.07);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (2, 19, 12, 2, 39.25);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (3, 19, 3, 4, 20.47);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (4, 20, 17, 1, 8.45);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (5, 1, 16, 4, 31.77);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (6, 19, 18, 3, 33.58);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (7, 10, 14, 5, 31.19);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (8, 19, 1, 3, 10.68);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (9, 18, 12, 3, 18.28);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (10, 16, 2, 1, 48.81);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (11, 17, 12, 3, 28.51);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (12, 13, 2, 5, 27.3);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (13, 14, 5, 3, 41.13);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (14, 7, 11, 3, 6.81);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (15, 11, 7, 3, 30.69);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (16, 14, 18, 3, 12.71);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (17, 2, 2, 5, 37.68);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (18, 5, 15, 3, 40.06);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (19, 18, 4, 2, 49.07);
INSERT INTO ORDER_DETAILS (ORDER_DETAIL_ID, ORDER_ID, ITEM_ID, QUANTITY, ITEM_PRICE) VALUES (20, 8, 9, 3, 41.78);

INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (1, 5, 'This is an announcement for Race 5.', '2025-07-26 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (2, 29, 'This is an announcement for Race 29.', '2025-04-13 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (3, 21, 'This is an announcement for Race 21.', '2025-06-04 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (4, 13, 'This is an announcement for Race 13.', '2025-05-17 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (5, 19, 'This is an announcement for Race 19.', '2025-08-12 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (6, 1, 'This is an announcement for Race 1.', '2025-07-23 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (7, 13, 'This is an announcement for Race 13.', '2025-08-28 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (8, 29, 'This is an announcement for Race 29.', '2025-08-30 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (9, 4, 'This is an announcement for Race 4.', '2025-01-02 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (10, 18, 'This is an announcement for Race 18.', '2025-09-11 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (11, 1, 'This is an announcement for Race 1.', '2025-01-01 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (12, 5, 'This is an announcement for Race 5.', '2025-03-19 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (13, 19, 'This is an announcement for Race 19.', '2025-02-10 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (14, 28, 'This is an announcement for Race 28.', '2025-09-28 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (15, 10, 'This is an announcement for Race 10.', '2025-09-20 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (16, 25, 'This is an announcement for Race 25.', '2025-10-02 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (17, 20, 'This is an announcement for Race 20.', '2025-07-10 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (18, 12, 'This is an announcement for Race 12.', '2025-04-07 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (19, 26, 'This is an announcement for Race 26.', '2025-02-06 00:00:00');
INSERT INTO ANNOUNCEMENTS (ANNOUNCEMENT_ID, RACE_ID, ANNOUNCEMENT_TEXT, ANNOUNCEMENT_DATE) VALUES (20, 12, 'This is an announcement for Race 12.', '2025-02-18 00:00:00');

INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS) VALUES (1, 'Admin', 'Administrator role with full access', '{"read": true, "write": true, "delete": true}');
INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS) VALUES (2, 'Manager', 'Manager role with limited administrative access', '{"read": true, "write": true, "delete": false}');
INSERT INTO ROLES (ROLE_ID, ROLE_NAME, DESCRIPTION, PERMISSIONS) VALUES (3, 'User', 'Regular user role with basic permissions', '{"read": true, "write": false, "delete": false}');


INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (1, 'User1 FullName', 'user1@example.com', 'user1', 'hashedpassword1', '555-000-0001', TRUE, 2, 'Active');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (2, 'User2 FullName', 'user2@example.com', 'user2', 'hashedpassword2', '555-000-0002', FALSE, 3, 'Active');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (3, 'User3 FullName', 'user3@example.com', 'user3', 'hashedpassword3', '555-000-0003', TRUE, 3, 'Inactive');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (4, 'User4 FullName', 'user4@example.com', 'user4', 'hashedpassword4', '555-000-0004', TRUE, 3, 'Inactive');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (5, 'User5 FullName', 'user5@example.com', 'user5', 'hashedpassword5', '555-000-0005', FALSE, 2, 'Active');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (6, 'User6 FullName', 'user6@example.com', 'user6', 'hashedpassword6', '555-000-0006', FALSE, 1, 'Inactive');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (7, 'User7 FullName', 'user7@example.com', 'user7', 'hashedpassword7', '555-000-0007', TRUE, 1, 'Active');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (8, 'User8 FullName', 'user8@example.com', 'user8', 'hashedpassword8', '555-000-0008', TRUE, 1, 'Active');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (9, 'User9 FullName', 'user9@example.com', 'user9', 'hashedpassword9', '555-000-0009', FALSE, 3, 'Active');
INSERT INTO USERS (USER_ID, FULL_NAME, EMAIL, USERNAME, PASSWORD_HASH, PHONE_NUMBER, IS_ADMIN, ROLE_ID, STATUS) VALUES (10, 'User10 FullName', 'user10@example.com', 'user10', 'hashedpassword10', '555-000-0010', TRUE, 2, 'Active');


INSERT INTO ADMINS (ADMIN_ID, USER_ID, ASSIGNED_DATE, ADMIN_TYPE) VALUES (1, 1, '2023-02-02', 'SuperAdmin');
INSERT INTO ADMINS (ADMIN_ID, USER_ID, ASSIGNED_DATE, ADMIN_TYPE) VALUES (2, 8, '2024-02-27', 'Manager');
INSERT INTO ADMINS (ADMIN_ID, USER_ID, ASSIGNED_DATE, ADMIN_TYPE) VALUES (3, 4, '2023-05-30', 'SuperAdmin');


INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (1, 22, 19, 15, 623.35, 8.26, 'Win', 5148.87);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (2, 18, 21, 5, 729.14, 7.68, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (3, 14, 38, 12, 982.34, 8.37, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (4, 8, 26, 12, 851.74, 4.54, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (5, 9, 7, 6, 452.79, 2.54, 'Win', 1150.09);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (6, 19, 31, 1, 816.53, 8.17, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (7, 16, 28, 9, 28.86, 8.17, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (8, 21, 20, 1, 100.38, 1.5, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (9, 7, 40, 14, 460.81, 6.75, 'Loss', 0);
INSERT INTO BETTING (BET_ID, RACE_ID, HORSE_ID, MEMBER_ID, BET_AMOUNT, ODDS, BET_OUTCOME, PAYOUT) VALUES (10, 28, 32, 2, 437.26, 7.9, 'Win', 3454.35);

INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (1, 23, 5, 'General', 169.44);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (2, 3, 3, 'General', 120.32);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (3, 15, 13, 'General', 122.63);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (4, 3, 14, 'VIP', 423.09);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (5, 24, 2, 'General', 129.49);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (6, 24, 4, 'General', 93.0);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (7, 28, 11, 'VIP', 213.62);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (8, 11, 11, 'VIP', 460.85);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (9, 22, 12, 'General', 92.77);
INSERT INTO TICKETS (TICKET_ID, RACE_ID, MEMBER_ID, TICKET_TYPE, PRICE) VALUES (10, 17, 12, 'General', 190.64);

INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (1, 6, 36, 1, '00:08:14');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (2, 5, 30, 8, '00:06:09');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (3, 9, 12, 2, '00:07:41');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (4, 26, 25, 4, '00:02:02');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (5, 26, 28, 8, '00:08:29');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (6, 21, 8, 4, '00:07:29');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (7, 30, 11, 2, '00:09:52');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (8, 21, 34, 4, '00:02:12');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (9, 14, 30, 7, '00:01:44');
INSERT INTO RACE_RESULTS (RESULT_ID, RACE_ID, HORSE_ID, POSITION, TIME_TAKEN) VALUES (10, 24, 33, 9, '00:05:11');

INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (1, 1, 5148.87, '2025-07-02 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (2, 5, 1150.09, '2025-07-27 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (3, 10, 3454.35, '2025-03-19 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (4, 6, 1635.28, '2025-01-09 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (5, 7, 1543.12, '2025-05-06 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (6, 4, 2010.02, '2025-01-07 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (7, 8, 378.15, '2025-10-17 00:00:00');
INSERT INTO BETTING_PAYOUTS (PAYOUT_ID, BET_ID, AMOUNT, PAYMENT_DATE) VALUES (8, 9, 3502.81, '2025-09-20 00:00:00');

UPDATE races SET RACE_NAME = 'Kentucky Derby' WHERE race_id = 1;
UPDATE races SET RACE_NAME = 'Preakness Stakes' WHERE race_id = 2;
UPDATE races SET RACE_NAME = 'Belmont Stakes' WHERE race_id = 3;
UPDATE races SET RACE_NAME = 'Breeders’ Cup Classic' WHERE race_id = 4;
UPDATE races SET RACE_NAME = 'Dubai World Cup' WHERE race_id = 5;
UPDATE races SET RACE_NAME = 'Melbourne Cup' WHERE race_id = 6;
UPDATE races SET RACE_NAME = 'Grand National' WHERE race_id = 7;
UPDATE races SET RACE_NAME = 'Epsom Derby' WHERE race_id = 8;
UPDATE races SET RACE_NAME = 'Prix de l’Arc de Triomphe' WHERE race_id = 9;
UPDATE races SET RACE_NAME = 'Travers Stakes' WHERE race_id = 10;
UPDATE races SET RACE_NAME = 'Haskell Invitational' WHERE race_id = 11;
UPDATE races SET RACE_NAME = 'Metropolitan Handicap' WHERE race_id = 12;
UPDATE races SET RACE_NAME = 'Whitney Stakes' WHERE race_id = 13;
UPDATE races SET RACE_NAME = 'Woodward Stakes' WHERE race_id = 14;
UPDATE races SET RACE_NAME = 'Pacific Classic' WHERE race_id = 15;
UPDATE races SET RACE_NAME = 'Santa Anita Derby' WHERE race_id = 16;
UPDATE races SET RACE_NAME = 'Arkansas Derby' WHERE race_id = 17;
UPDATE races SET RACE_NAME = 'Florida Derby' WHERE race_id = 18;
UPDATE races SET RACE_NAME = 'Blue Grass Stakes' WHERE race_id = 19;
UPDATE races SET RACE_NAME = 'Louisiana Derby' WHERE race_id = 20;
UPDATE races SET RACE_NAME = 'Irish Derby' WHERE race_id = 21;
UPDATE races SET RACE_NAME = 'Queen’s Plate' WHERE race_id = 22;
UPDATE races SET RACE_NAME = 'King George VI & Queen Elizabeth Stakes' WHERE race_id = 23;
UPDATE races SET RACE_NAME = 'Cox Plate' WHERE race_id = 24;
UPDATE races SET RACE_NAME = 'Golden Slipper Stakes' WHERE race_id = 25;
UPDATE races SET RACE_NAME = 'Japan Cup' WHERE race_id = 26;
UPDATE races SET RACE_NAME = 'Pegasus World Cup' WHERE race_id = 27;
UPDATE races SET RACE_NAME = 'Hollywood Gold Cup' WHERE race_id = 28;
UPDATE races SET RACE_NAME = 'Jockey Club Gold Cup' WHERE race_id = 29;
UPDATE races SET RACE_NAME = 'Dubai Sheema Classic' WHERE race_id = 30;
